repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-vcs-permalinks
    - id: destroyed-symlinks
    - id: detect-private-key
    - id: mixed-line-ending
    - id: trailing-whitespace
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.89.1
  hooks:
    - id: terraform_validate
      args:
        - --hook-config=--retry-once-with-cleanup=true
        - --args=-no-color
        - --tf-init-args=-reconfigure
        - --tf-init-args=-upgrade
    - id: terraform_tflint
      args:
        - --args=--minimum-failure-severity=error
        - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
    - id: terraform_tfsec
      args:
        - --args=--config-file=__GIT_WORKING_DIR__/.tfsec.yml
        - --args=--tfvars-file=__GIT_WORKING_DIR__/terraform.tfvars
        - --args=--soft-fail
    - id: terraform_checkov
      args:
        - --args=--config-file __GIT_WORKING_DIR__/.checkov.yml
    - id: terraform_fmt
      args:
        - --args=-no-color
        - --args=-diff
        - --args=-recursive
    - id: terraform_docs
      args:
        - --args=--config=.terraform-docs.yml