---
name: Build & Push to ghcr.io
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Build docker image
        run: docker build -t ghcr.io/makeitworkcloud/terraform-runner:latest .

      - name: Push docker image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/makeitworkcloud/terraform-runner:latest